---
services:
  database:
    image: pgvector/pgvector:pg16
    hostname: postgres
    container_name: postgres
    restart: always
    shm_size: 8gb
    volumes:
      - ./database:/var/lib/postgresql/data:rw
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - db.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
  ollama_container:
    image: ollama/ollama:0.3.3
    hostname: ollama_container
    container_name: ollama_container
    restart: always
    mem_limit: 8g
    cpus: 6 
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_FLASH_ATTENTION=1
      #- OLLAMA_DEBUG=1
      # - OLLAMA_MAX_LOADED_MODELS=1
    volumes:
      - ./ollama:/root/.ollama
    expose:
      - 11434/tcp
    ports:
      - 11434:11434
    entrypoint: ollama serve
    healthcheck:
      test: ollama --version || exit 1
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         # Below setting allow Ollama to use Nvidia GPUs to run the models.
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
  train_store:
    depends_on:
      database:
        condition: service_healthy
      ollama_container:
        condition: service_healthy
    build:
      context: ./train_store
    hostname: train_store
    container_name: train_store
    image: train_store
    restart: always
    working_dir: /usr/train_store/
    read_only: false
    volumes:
      - ./train_store:/usr/train_store/
    entrypoint: /bin/bash /usr/train_store/entrypoint.sh
    security_opt:
      - no-new-privileges:true
    env_file:
      - db.env
    environment:
      - db_port=5432
      - db_host=postgres
      - db_name=postgres
      - db_user=postgres
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080"]
      interval: 10s
      timeout: 30s
      retries: 5